import pytest
from fixtures.fixture_titanic import TitanicFixture
from fixtures.fixture_bird import BirdFixture
from fixtures.fixture_faces import FacesFixture
from fixtures.fixture_movies import MovieFixture
from fixtures.fixture_handwriting import HandwritingFixture
from fixtures.fixture_cardiac import CardiacFixture
